name: Publish
on:
  workflow_dispatch:
    inputs:
      runner:
        type: string

jobs:
  publish:
    name: Publish
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd .\Mediapipe.Net\  
          dotnet build .\Mediapipe.Net.csproj
          nuget.exe pack .\Mediapipe.Net.csproj -symbols
          nuget push *.nupkg ${{secrets.NUGET_TOKEN}} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
          7z a -tzip output.zip bin/debug/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-output
          path: ${{ github.workspace }}/output.zip
          retention-days: 1
